spring:
  application:
    name: UTECareerBridge-BE
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SERVICE_USERNAME}
    password: ${MAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: false
access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key
refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key
app:
  password-reset:
    expirations: 15
  frontend:
    url: http://localhost:3000
api:
  prefix: /api/v1
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.pn.career: DEBUG
firebase:
  configuration: firebase-adminsdk.json

